
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const TodoStatus = {
  PENDING: 'PENDING',
  DONE: 'DONE',
  REMINDER_DUE: 'REMINDER_DUE'
} as const

export type TodoStatus = (typeof TodoStatus)[keyof typeof TodoStatus]
